name: linux 64 bit build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps: 
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install wireguard-tools libgtk-3-dev libayatana-appindicator3-dev golang-go
      - name: Compile
        run: | 
          ./package.sh
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: artifacts
          path: |
            build
